version: '3.4'
services:
  db:
    image: postgres:13.1
    container_name: db
    environment:
      POSTGRES_DB: "equeue"
      POSTGRES_USERNAME: "queue_password"
      POSTGRES_PASSWORD: "queue_password"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  manager_kit_server:
    container_name: equeue_server
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/equeue
      - SPRING_DATASOURCE_USERNAME=queue_password
      - SPRING_DATASOURCE_PASSWORD=queue_password
      - CLIENT_IDS=${CLIENT_IDS}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - NOTIFICATION_SECRET=${NOTIFICATION_SECRET}
      - SECRET=${SECRET}