server:
  port: 8080
  compression:
    enabled: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATABASE_URL:jdbc:postgresql://localhost:5432/Equeue}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    show-sql: true
    properties:
      types:
        print:
          banner: false
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    change-log: db/changelog-master.xml

android:
  clientId: ${CLIENT_IDS}

jwt:
  secret: ${SECRET}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: eu-north-1
    stack:
      auto: false
    bucket:
      name: electronicqueue


springdoc:
  swagger-ui:
    path: /swagger-ui/api-doc
    operationsSorter: method
